// Generated by CoffeeScript 1.10.0
(function() {
  $.form = function(post) {
    var done;
    $.form.send = function(post) {
      $.ajax({
        type: "post",
        url: "php/index.php",
        cache: false,
        data: post,
        async: false
      }).done(function(data) {
        return post = data;
      });
      return $.parseJSON(post);
    };
    done = $.form.send({
      "ajax": post
    });
    return done;
  };

  if (!$.appCtrl) {
    $.appCtrl = {};
  }

  if (!$.appCtrl.goto) {
    $.appCtrl.goto = {};
  }

  $.appCtrl = function(post) {
    var i, temp;
    temp = {
      '_proccess': {
        '_true': false,
        'goto': {}
      },
      '_erro': {
        '_true': false
      },
      '_warning': {
        '_true': false
      },
      '_done': {
        '_true': false
      },
      'appCtrl': {}
    };
    temp._proccess.post = false;
    if (post.length >= 1) {
      temp._proccess.post = true;
    }
    if (temp._proccess.post === true) {
      i = 0;
      while (i < post.length) {
        temp.appCtrl[i] = {};
        temp.appCtrl[i]["this"] = $(post)[i];
        temp.appCtrl[i].app = $(post).data().appCtrl;
        if (temp.appCtrl[i].app.goto) {
          temp._proccess.goto[i] = {};
          temp._proccess.goto[i] = $.appCtrl.goto(temp.appCtrl[i]);
        }
        i++;
      }
    }
    return console.log(temp);
  };

  $.appCtrl.goto = function(post) {
    var temp;
    temp = {
      '_proccess': {
        '_true': false
      },
      '_erro': {
        '_true': false
      },
      '_warning': {
        '_true': false
      },
      '_done': {
        '_true': false
      }
    };
    if (post.app.goto.id) {
      temp._done = 'Ainda nao existe tratamento em ID';
    } else if (post.app.goto.css) {
      temp._done = 'Ainda nao existe tratamento em CLASS';
    } else if (post.app.goto.cover) {
      temp._proccess.cover = false;
      $(post["this"]).click(function() {
        $('#app-capa').addClass('page-out');
        return temp._proccess.cover = true;
      });
    }
    return temp;
  };

  $.appCtrl($("[data-app-ctrl]"));

}).call(this);
